// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantAlloraProjectData;

#nullable disable

namespace RestaurantAlloraProjectData.Migrations
{
    [DbContext(typeof(RestaurantAlloraProjectContext))]
    partial class RestaurantAlloraProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Allergen", b =>
                {
                    b.Property<Guid>("AllergenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllergenName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("AllergenId");

                    b.ToTable("Allergens");

                    b.HasData(
                        new
                        {
                            AllergenId = new Guid("dc08b4ec-5095-4811-a672-192301357e16"),
                            AllergenName = "Зърнени култури, съдържащи глутен: пшеница, ръж, ечемик, овес, спелта, камут, както и продукти от тях"
                        },
                        new
                        {
                            AllergenId = new Guid("42ccb79f-216b-4aab-9655-944d4f7b9823"),
                            AllergenName = "Ракообразни и продукти от тях"
                        },
                        new
                        {
                            AllergenId = new Guid("c4399ef7-4776-4b45-92fb-35ae3dd3f977"),
                            AllergenName = "Яйца и продукти от тях"
                        },
                        new
                        {
                            AllergenId = new Guid("bcccc627-fc03-40cc-bfb4-9047d4626528"),
                            AllergenName = "Риба и рибни продукти"
                        },
                        new
                        {
                            AllergenId = new Guid("fe83dc00-a553-4041-8e2e-aa7c9eb5a0ed"),
                            AllergenName = "Фъстъци и продукти от тях"
                        },
                        new
                        {
                            AllergenId = new Guid("503510df-d3a4-4266-a182-3b3db962de57"),
                            AllergenName = "Соя и соеви продукти"
                        },
                        new
                        {
                            AllergenId = new Guid("a846b85f-53b1-4b2a-b096-825824c3b7e2"),
                            AllergenName = "Мляко и млечни продукти (включително лактоза)"
                        },
                        new
                        {
                            AllergenId = new Guid("247f192a-3e44-480a-bde9-98089f8b398b"),
                            AllergenName = "Ядки – бадеми, орехи, лешници, кашу и др."
                        },
                        new
                        {
                            AllergenId = new Guid("3a8c6114-15c6-4f6c-9de1-21126a38706f"),
                            AllergenName = "Целина и продукти от нея"
                        },
                        new
                        {
                            AllergenId = new Guid("7d1e6d36-e29a-40ca-970a-3c016cfb7a99"),
                            AllergenName = "Синап и продукти от него"
                        },
                        new
                        {
                            AllergenId = new Guid("7f4554e9-9835-479e-bb37-b97ed9c58d6a"),
                            AllergenName = "Сусамово семе и продукти от него"
                        },
                        new
                        {
                            AllergenId = new Guid("6ab84643-d4db-4789-bf18-f43afe7e4a38"),
                            AllergenName = "Лупина и продукти от нея"
                        },
                        new
                        {
                            AllergenId = new Guid("64d4fbb0-ffe7-4526-9d18-300608276013"),
                            AllergenName = "Серен диоксид и сулфити с концентрация над 10 mg/kg или 10 mg/l"
                        },
                        new
                        {
                            AllergenId = new Guid("6b990dac-6b4f-49f4-a715-ccaa67246c3e"),
                            AllergenName = "Мекотели и продукти от тях"
                        });
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("a19f1c7a-0a27-4c91-a220-2f4c55fb0b21"),
                            Name = "Салати"
                        },
                        new
                        {
                            CategoryId = new Guid("0a55dc5d-23b6-4c3a-8428-3f0f7f370aa6"),
                            Name = "Основни ястия"
                        },
                        new
                        {
                            CategoryId = new Guid("b3cb4f8b-8f1c-44f7-a332-3f2d2bb24b0b"),
                            Name = "Десерти"
                        },
                        new
                        {
                            CategoryId = new Guid("aeae6939-7449-467f-b1d6-b0cbd340fc7d"),
                            Name = "Напитки"
                        });
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.CustomerFavorite", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("CustomerFavorites");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.CustomerOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrderId");

                    b.ToTable("CustomerOrderItems");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.CustomerProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.ToTable("CustomerProfile");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Dish", b =>
                {
                    b.Property<Guid>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryOfTheDish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescriptionOfTheDish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfTheDish")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PriceOfTheDish")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DishId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.DishAllergen", b =>
                {
                    b.Property<Guid>("DishId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AllergenId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DishId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("DishAllergens");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.EmployeeProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId");

                    b.ToTable("EmployeeProfile");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerFullName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FulfillmentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Вземане на място");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Обработва се");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Очаква одобрение");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReservationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TableId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("DishId");

                    b.HasIndex("CustomerId", "DishId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Table", b =>
                {
                    b.Property<Guid>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapacityOfTheTable")
                        .HasColumnType("int");

                    b.Property<string>("StatusOfTheTable")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Свободна");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("TableId");

                    b.HasIndex("TableNumber")
                        .IsUnique();

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 1
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000002"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 2
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000003"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 3
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000004"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 4
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000005"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 5
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000006"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 6
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000007"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 7
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000008"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 8
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000009"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 9
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000010"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 10
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000011"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 11
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000012"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 12
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000013"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 13
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000014"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 14
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000015"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 15
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000016"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 16
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000017"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 17
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000018"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 18
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000019"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 19
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000020"),
                            CapacityOfTheTable = 2,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 20
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000021"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 21
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000022"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 22
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000023"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 23
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000024"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 24
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000025"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 25
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000026"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 26
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000027"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 27
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000028"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 28
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000029"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 29
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000030"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 30
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000031"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 31
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000032"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 32
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000033"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 33
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000034"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 34
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000035"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 35
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000036"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 36
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000037"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 37
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000038"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 38
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000039"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 39
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000040"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 40
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000041"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 41
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000042"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 42
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000043"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 43
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000044"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 44
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000045"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 45
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000046"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 46
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000047"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 47
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000048"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 48
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000049"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 49
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000050"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 50
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000051"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 51
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000052"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 52
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000053"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 53
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000054"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 54
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000055"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 55
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000056"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 56
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000057"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 57
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000058"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 58
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000059"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 59
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000060"),
                            CapacityOfTheTable = 4,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 60
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000061"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 61
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000062"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 62
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000063"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 63
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000064"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 64
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000065"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 65
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000066"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 66
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000067"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 67
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000068"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 68
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000069"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 69
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000070"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 70
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000071"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 71
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000072"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 72
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000073"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 73
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000074"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 74
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000075"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 75
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000076"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 76
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000077"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 77
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000078"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 78
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000079"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 79
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000080"),
                            CapacityOfTheTable = 6,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 80
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000081"),
                            CapacityOfTheTable = 8,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 81
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000082"),
                            CapacityOfTheTable = 8,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 82
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000083"),
                            CapacityOfTheTable = 8,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 83
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000084"),
                            CapacityOfTheTable = 8,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 84
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000085"),
                            CapacityOfTheTable = 8,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 85
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000086"),
                            CapacityOfTheTable = 8,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 86
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000087"),
                            CapacityOfTheTable = 8,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 87
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000088"),
                            CapacityOfTheTable = 8,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 88
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000089"),
                            CapacityOfTheTable = 8,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 89
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000090"),
                            CapacityOfTheTable = 8,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 90
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000091"),
                            CapacityOfTheTable = 10,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 91
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000092"),
                            CapacityOfTheTable = 10,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 92
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000093"),
                            CapacityOfTheTable = 10,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 93
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000094"),
                            CapacityOfTheTable = 10,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 94
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000095"),
                            CapacityOfTheTable = 10,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 95
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000096"),
                            CapacityOfTheTable = 10,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 96
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000097"),
                            CapacityOfTheTable = 10,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 97
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000098"),
                            CapacityOfTheTable = 10,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 98
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000099"),
                            CapacityOfTheTable = 10,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 99
                        },
                        new
                        {
                            TableId = new Guid("10000000-0000-0000-0000-000000000100"),
                            CapacityOfTheTable = 10,
                            StatusOfTheTable = "Свободна",
                            TableNumber = 100
                        });
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RestaurantAlloraProjectData.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RestaurantAlloraProjectData.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAlloraProjectData.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RestaurantAlloraProjectData.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.CustomerFavorite", b =>
                {
                    b.HasOne("RestaurantAlloraProjectData.Entities.CustomerProfile", "Customer")
                        .WithMany("Favorites")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAlloraProjectData.Entities.Dish", "Dish")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.CustomerOrderItem", b =>
                {
                    b.HasOne("RestaurantAlloraProjectData.Entities.Dish", "Dish")
                        .WithMany("OrderItems")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantAlloraProjectData.Entities.EmployeeProfile", "Employee")
                        .WithMany("HandledOrders")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RestaurantAlloraProjectData.Entities.Order", "Order")
                        .WithMany("CustomerOrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Employee");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.CustomerProfile", b =>
                {
                    b.HasOne("RestaurantAlloraProjectData.Entities.User", "User")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("RestaurantAlloraProjectData.Entities.CustomerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Dish", b =>
                {
                    b.HasOne("RestaurantAlloraProjectData.Entities.Category", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.DishAllergen", b =>
                {
                    b.HasOne("RestaurantAlloraProjectData.Entities.Allergen", "Allergen")
                        .WithMany("DishAllergens")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAlloraProjectData.Entities.Dish", "Dish")
                        .WithMany("DishAllergens")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.EmployeeProfile", b =>
                {
                    b.HasOne("RestaurantAlloraProjectData.Entities.User", "User")
                        .WithOne("EmployeeProfile")
                        .HasForeignKey("RestaurantAlloraProjectData.Entities.EmployeeProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Order", b =>
                {
                    b.HasOne("RestaurantAlloraProjectData.Entities.CustomerProfile", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Reservation", b =>
                {
                    b.HasOne("RestaurantAlloraProjectData.Entities.CustomerProfile", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantAlloraProjectData.Entities.EmployeeProfile", "Employee")
                        .WithMany("HandledReservations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RestaurantAlloraProjectData.Entities.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Review", b =>
                {
                    b.HasOne("RestaurantAlloraProjectData.Entities.CustomerProfile", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantAlloraProjectData.Entities.Dish", "Dish")
                        .WithMany("Reviews")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Allergen", b =>
                {
                    b.Navigation("DishAllergens");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Category", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.CustomerProfile", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Orders");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Dish", b =>
                {
                    b.Navigation("DishAllergens");

                    b.Navigation("FavoritedBy");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.EmployeeProfile", b =>
                {
                    b.Navigation("HandledOrders");

                    b.Navigation("HandledReservations");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Order", b =>
                {
                    b.Navigation("CustomerOrderItems");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.Table", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RestaurantAlloraProjectData.Entities.User", b =>
                {
                    b.Navigation("CustomerProfile");

                    b.Navigation("EmployeeProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
